if [[ -o 'aliases' ]]; then
  # Temporarily disable aliases.
  'builtin' 'unsetopt' 'aliases'
  local p9k_classic_restore_aliases=1
else
  local p9k_classic_restore_aliases=0
fi

() {
  emulate -L zsh
  setopt no_unset extended_glob
  zmodload zsh/langinfo
  if [[ ${langinfo[CODESET]:-} != (utf|UTF)(-|)8 ]]; then
    local LC_ALL=${${(@M)$(locale -a):#*.(utf|UTF)(-|)8}[1]:-en_US.UTF-8}
  fi

  # Unset all configuration options. This allows you to apply configiguration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m 'POWERLEVEL9K_*'

  POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER// }'

  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=''

  #gruvbox colors
  GRUVBOX_FG0=229
  GRUVBOX_FG1=223
  GRUVBOX_FG2=250
  GRUVBOX_FG3=248
  GRUVBOX_FG4=246
  GRUVBOX_BG0=235
  GRUVBOX_BG1=237
  GRUVBOX_BG2=239
  GRUVBOX_BG3=241
  GRUVBOX_BG4=243
  GRUVBOX_BG0_S=236

  # Easily switch primary foreground/background colors
  DEFAULT_FOREGROUND=$GRUVBOX_FG1
  DEFAULT_BACKGROUND=$GRUVBOX_BG0
  DEFAULT_ACCENT=$GRUVBOX_FG2
  DEFAULT_COLOR=$DEFAULT_FOREGROUND

  POWERLEVEL9K_MODE="nerdfont-complete"
  #POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  #POWERLEVEL9K_SHORTEN_STRATEGY="truncate_right"

  POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false

  POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
  POWERLEVEL9K_ALWAYS_SHOW_USER=false

  POWERLEVEL9K_CONTEXT_TEMPLATE="\uF109 %u"

  POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="$DEFAULT_BACKGROUND"

  POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0B4"
  POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}|%f"
  POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\uE0B6"
  POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}|%f"

  POWERLEVEL9K_PROMPT_ON_NEWLINE=true
  POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

  POWERLEVEL9K_STATUS_VERBOSE=true
  POWERLEVEL9K_STATUS_CROSS=true
  POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  CONNECTOR_COLOR=$GRUVBOX_FG1
  FIRST_ARROW_COLOR=$GRUVBOX_FG1
  SECOND_ARROW_COLOR=$GRUVBOX_FG3
  THIRD_ARROW_COLOR=$GRUVBOX_FG4

  POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{CONNECTOR_COLOR}\u256D\u2500%f"
  POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{CONNECTOR_COLOR}\u2570%F{$FIRST_ARROW_COLOR}\uF0DA%F{$SECOND_ARROW_COLOR}\uF0DA%F{$THIRD_ARROW_COLOR}\uF0DA%f "

  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(host root_indicator dir_writable dir vcs)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time background_jobs status)

  POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false

  POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
  POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"
  POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="magenta"
  POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$DEFAULT_BACKGROUND"

  POWERLEVEL9K_DIR_HOME_BACKGROUND="$GRUVBOX_FG2"
  POWERLEVEL9K_DIR_HOME_FOREGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="$GRUVBOX_FG2"
  POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="$GRUVBOX_FG2"
  POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="$GRUVBOX_FG2"
  POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="$DEFAULT_BACKGROUND"

  POWERLEVEL9K_STATUS_OK_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
  POWERLEVEL9K_STATUS_OK_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_STATUS_OK_BACKGROUND="$(( $DEFAULT_BACKGROUND + 3 ))"

  POWERLEVEL9K_STATUS_ERROR_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
  POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$(( $DEFAULT_BACKGROUND + 3 ))"

  POWERLEVEL9K_HISTORY_FOREGROUND="$DEFAULT_FOREGROUND"

  POWERLEVEL9K_TIME_FORMAT="%D{%T}"
  POWERLEVEL9K_TIME_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_TIME_BACKGROUND="$DEFAULT_BACKGROUND"

  POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
  POWERLEVEL9K_VCS_GIT_ICON=""

  POWERLEVEL9K_VCS_UNTRACKED_ICON="\uF059"
  POWERLEVEL9K_VCS_UNSTAGED_ICON="\uF06A"
  POWERLEVEL9K_VCS_STAGED_ICON="\uF055"
  POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON="\uF01A "
  POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="\uF01B "
  POWERLEVEL9K_VCS_TAG_ICON="\uF02B "
  POWERLEVEL9K_VCS_BOOKMARK_ICON="\uF461"
  POWERLEVEL9K_VCS_COMMIT_ICON="\uE729 "
  POWERLEVEL9K_OK_ICON="\uF00C"
  POWERLEVEL9K_HOME_ICON="\uF015"

  POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="$(( $DEFAULT_BACKGROUND + 5 ))"
  POWERLEVEL9K_EXECUTION_TIME_ICON="\uF252"

  POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
  #POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0

  POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="$DEFAULT_FOREGROUND"

  POWERLEVEL9K_USER_ICON="\uF415"
  POWERLEVEL9K_USER_DEFAULT_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_USER_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_USER_ROOT_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_USER_ROOT_BACKGROUND="$DEFAULT_BACKGROUND"

  POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="magenta"
  POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$(( $DEFAULT_BACKGROUND + 2 ))"
  POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$(( $DEFAULT_BACKGROUND - 2 ))"
  POWERLEVEL9K_ROOT_ICON=$'\uF198'

  POWERLEVEL9K_SSH_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_SSH_FOREGROUND="yellow"
  POWERLEVEL9K_SSH_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_SSH_BACKGROUND="$(( $DEFAULT_BACKGROUND + 2 ))"
  POWERLEVEL9K_SSH_BACKGROUND="$(( $DEFAULT_BACKGROUND - 2 ))"
  POWERLEVEL9K_SSH_ICON="\uF489"

  POWERLEVEL9K_HOST_LOCAL_FOREGROUND="$GRUVBOX_FG2"
  POWERLEVEL9K_HOST_LOCAL_BACKGROUND="$GRUVBOX_BG0"
  POWERLEVEL9K_HOST_REMOTE_FOREGROUND="$GRUVBOX_FG2"
  POWERLEVEL9K_HOST_REMOTE_BACKGROUND="$GRUVBOX_BG0"

  POWERLEVEL9K_HOST_ICON="\uF197"
  #POWERLEVEL9K_HOST_ICON="\uf6f5"
  POWERLEVEL9K_HOST_TEMPLATE=""

  POWERLEVEL9K_OS_ICON_FOREGROUND="$DEFAULT_FOREGROUND"
  POWERLEVEL9K_OS_ICON_BACKGROUND="$DEFAULT_BACKGROUND"

  POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_LOAD_WARNING_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="red"
  POWERLEVEL9K_LOAD_WARNING_FOREGROUND="yellow"
  POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="green"
  POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
  POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
  POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"

  POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND_COLOR="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="$DEFAULT_BACKGROUND"
  POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="$DEFAULT_BACKGROUND"
}

(( ! p9k_classic_restore_aliases )) || setopt aliases
'builtin' 'unset' 'p9k_classic_restore_aliases'
